Frontend/index.html, Frontend/script.js, Frontend/style.css
Fixes: #4 
This PR improves the Dark Mode functionality by adding:
✅ Dark/Light Mode Toggle Button with a 🌞/🌙 emoji indicator.
✅ Better UI Styling for dark mode (improved contrast, smooth transitions).
✅ Enhanced Readability: Lightened paragraph text color for better visibility.
✅ Refactored Code: Cleaned up CSS and optimized dark mode handling.
Here’s how the UI looked before the improvements:
! [Light1] (https://github.com/user-attachments/assets/21ec1858-be79-4e2d-b974-77167cece544)
! [Light2] (https://github.com/user-attachments/assets/e06c9857-93b3-469d-b8c6-c43807b9bf72)
Here’s how the UI looked after the improvements:
=> Added dark mode toggle button with emoji

Frontend/index.html, Frontend/script.js, Frontend/style.css
I have added footer with newsletter subscription, secondary navigation link, social sharing under issue #9
=> enhanced footer

Frontend/index.html, Frontend/script.js, Frontend/style.css
Fixes: #20 
Implemented a dynamic greeting system based on time.
Improved user experience with personalized messages.
Ensured compatibility with both light and dark modes.
Before implementation:
After implementation:
=> Added greeting feature

Frontend/index.html, Frontend/script.js, Frontend/style.css
Fixes: #22 
- Added an alert box that displays a greeting message when the website is loaded.
- Greeting message changes based on the time of day.
. Tested locally, working as expected.
After implementation:
=> Added greeting alert feature on page load

Frontend/index.html, Frontend/login.css, Frontend/login.html, Frontend/script.js, Frontend/signup.css, Frontend/signup.html, Frontend/style.css, Frontend/toggle.css, Frontend/toggle.js
Fixed: #28 
sign up and login page is made as per you say, and it contain proper authentication with email,password
=> Registration pages done

Frontend/feedback.html, Frontend/index.html
#10  I have finished adding the feedback page. Kindly merge.
=> Feedback form added

Frontend/index.html, Frontend/script.js, Frontend/style.css
Fixes: #36 
✅ Implemented a typing effect animation for the navbar title ("Coding Club").
✅ The cursor blinks while typing but disappears after completion for a clean UI.
✅ Ensured smooth user experience by adjusting timing and speed.
Why This Change?
. Makes the header more dynamic and engaging.
. Improves visual appeal and branding of the Coding Club website.
Working:
The text types letter by letter using setTimeout().
Once complete, the cursor effect (border-right) disappears.
=> Added typing effect on Navbar title (Coding Club)

Frontend/index.html, Frontend/script.js, Frontend/style.css
This update improves the website's mobile responsiveness by refining the navbar design and introducing a hamburger menu for better navigation on smaller screens.
- **Added a Hamburger Menu:** Implemented a responsive, interactive hamburger menu to enhance mobile usability. The menu smoothly opens and closes to provide easy access to navigation links.
- **Optimized Layout for Small Screens:** Adjusted the navbar structure to fit various screen sizes while maintaining a clean and user-friendly design.
- **Improved Styling & Alignment:** Ensured proper spacing, font sizes, and alignment for better readability and accessibility.
- **Smooth Animations & Transitions:** Added animations to enhance the opening/closing experience of the hamburger menu for a more dynamic feel.
- **Performance …
=> Improve Mobile Responsiveness for Navbar

Frontend/contributor.html, Frontend/index.html
Fixes: #71 
- added faq page with search functionality which is full responsive for any screens.
---
=> faq page added

Frontend/contributor.html, Frontend/index.html, Frontend/review.html
Review section page added in navbar
Fixes: #72 
Uploading Screen Recording 2025-02-17 233939.mp4…
- [.] Code follows project guidelines
- [] Proper documentation updated
- [.] Tested on local machine
---
=> Review section added

Frontend/contributor.html, Frontend/index.html, Frontend/review.html
navbar event link now redirect to only one event section, not separate page.
Fixes: #70 
- [. ] Fixed bug
---
=> Fixation done in event link of navbar

Frontend/privacy.html
scroll button added in privacy page
Fixes: #75 
---
=> scroll button added in privacy page

Frontend/privacy.html, Frontend/terms.html
scroll to top button added in terms page
Fixes: #76 
---
=> scroll to top button added in terms page

Frontend/privacy.html
navbar & footer added in privacy policy page
Fixes: #77 
---
=> navbar & footer added in privacy policy page

Frontend/privacy.html, Frontend/terms.html
Terms page navbar added. 
Fixes: #78 
---
=> Terms page navbar added

Frontend/privacy.html
Footer added in privacy page
---
=> Footer added in privacy page

Frontend/index.html
Animation Home
Fixes: #91 
- Animation Home is an engaging and interactive web page that utilizes the AOS (Animate On Scroll) Library to create smooth and eye-catching animations. It enhances user experience by adding dynamic motion effects to elements as they appear in the viewport.
https://github.com/user-attachments/assets/b05674f1-fc98-4088-9fb4-3877aa1350ed
---
=> Animation Home

Frontend/terms.html
Privacy policy link in terms and conditions not redirect to the privacy policy so i fixed that
Fixes: #82 
- [Privacy policy link in terms and conditions will redirect to the privacy policy ] Fixed bug
---
=> redirect link fixed

Frontend/style.css
Fixed the width of the navbar and the footer
Fixes: #84 
Fixed the width of the navbar and footer for smaller as well as  normal screens.
Previous:
After making changes:
https://github.com/user-attachments/assets/3175620f-ada6-409b-ba47-8b47c14a1fde
Thank You
---
=> Fixed the width of the navbar and the footer

.vscode/settings.json, Frontend/contributor.html, Frontend/index.html, Frontend/project.css, Frontend/projectpage.html, Frontend/review.html, Frontend/script.js, Frontend/terms.html
This PR introduces a dedicated Projects Page to the Coding Club website. It allows users to explore various projects with associated images and provides a search functionality to filter projects based on keywords.
- **Projects Page:** Displays a grid of projects, each with an image and brief description.
- **Search Functionality**: Allows users to filter projects by name or keywords, making it easy to find specific projects.
- **Responsive Design: The** page is designed to be fully responsive, ensuring proper display on both mobile and desktop devices.
- Added an array of project data (name, image, description) to dynamically render project cards.
- Implemented a search bar using JavaScript to filter projects based on user input.
- Applied CSS to ensure the layout is responsive and …
=>  Develop a Dedicated Projects Page with Images & Search Functionality

Frontend/feedback.js, Frontend/index.html
Added google sheets to store a feedbacks
Fixes: #74 
- [ Added Google sheets to store the user feedback data ] Added new feature
---
SETUP PROCEDURE
-In the Google Sheet, go to Extensions > Apps Script
-Paste this code
function doPost(e) {
try {
var name = e.parameter.name;
var email = e.parameter.email;
var phone = e.parameter.phone;
var feedback = e.parameter.feedback;
var subject=e.parameter.subject
var sheet = SpreadsheetApp.openById("**SHEET_ID**").getSheetByName("Sheet1");
sheet.appendRow([name, email, phone,subject, feedback, new Date()]);
return ContentService.createTextOutput("Form submitted successfully!")
.setMimeType(ContentService.MimeType.TEXT);
} catch (error) {
return ContentService.createTextOutput("Error: " + error.toString()) …
=> Feedback form

Frontend/index.html, Frontend/privacy.html, Frontend/projectpage.html
The privacy policy nav bar was not redirecting to othetr pages so i fixed that also adding the video
Fixes: #103 
- [
https://github.com/user-attachments/assets/45268cd2-5ae2-4003-921b-a698dc5c8c92
] Added new feature
---
BUG NOTE:
I found that the privacy policy page of the contributors page was not working while testing, I probaly think some one is working on it so i didn't raised any issue
=> Privacy redirect fixed

Frontend/style.css
Made the home section responsive
Fixes: #122 
The home section is now responsive for all dimensions  by using flex
Previous:
After making changes:
Thank You
---
=> Made the home section responsive for all dimensions

Frontend/event.html
more upcoming events with innovative names, descriptions and also changed the past events name, descriptions etc. previously it was same for the more & past events. 
Fixes: #125 
---
=> more event page enhanced

Frontend/privacy.html, Frontend/style.css, Frontend/terms.html
fixed the darmode issue of the privacy page
Fixes: #142 
- [ Fixed the issue of the privacy policy page reagrding the text color ] Fixed bug
---
=> Privacy policy page text color fix

Frontend/contributor.html, Frontend/privacy.html, Frontend/style.css, Frontend/terms.html
The feedback in the navbar was not redirecting to feedback so i fixed that
Fixes: #104 
- [ Fixed the 404 issue when on clicking the feedback] Fixed bug
https://github.com/user-attachments/assets/29c11f68-3bea-4ffd-93f3-fad0f5c9f81a
---
=> Contribute feed back

Frontend/review.html
fixed the title for the review page
Fixes: #163 
---
=> fixed the title for the review page

Frontend/index.html, Frontend/project.css, Frontend/projectpage.html, Frontend/style.css
Fixed the footer of the project page
Fixes: #148 
Fixed the footer of the project page by matching it's alignment
Previous:
Now:
Thank You
---
=> Fixed the footer of the project page

Frontend/style.css, Frontend/terms.html
Fixed teh dark mode issue for terms and condition page
Fixes: #143 
- [Fixed teh dark mode issue for terms and condition page ] Fixed bug
---
=> Fixed teh dark mode issue for terms and condition page

Frontend/index.html, Frontend/style.css
Added style to add event form and made it responsive
Fixes: #120 
Added styling to the add event form and also made it responsive
Before:
Now:
Thank You
---
=> Added style to add event form and made it responsive

Frontend/event.css, Frontend/event.html
Added the event form in the event page
Fixes: #114 
Added the event form to the event page and added styling to it with hover effects and made it responsive also for smaller screens.
Preview:
https://github.com/user-attachments/assets/970999a6-b378-45e8-a03d-60ab41591acb
Thank You
---
=> Added the event form in event page

Frontend/style.css
Fixed the responsiveness of the header of the event section
Fixes: #88 
Fixed the responsiveness of the event header section making it responsive for all screen sizes
Previous:
Now:
https://github.com/user-attachments/assets/e084acfe-a9ad-48c7-b7df-93c8f4572293
Thank You
---
=> Fixed the responsiveness of event section

Frontend/projectpage.html
Fixed the title of project page
Fixes: #206 
Changed the title of project page
Previous:
Now:
Thank You
---
=> Fixed the title of the page

Frontend/contributor.html, Frontend/test.txt
Fixed the Quick links for the contribute page
Fixes: #105 
- [ Fixed the Quick links for the contribute page] Fixed bug
---
=> Fixed the Quick links for the contribute page

Frontend/style.css
Faq answers visibility in dark mode fixed
Fixes: #115 
Fixed the visibility of faq answers in dark mode
Previous:
Now:
Thank You
---
=> Dark mode faq text visibility fixed

Frontend/index.html
=> Minor Ui Change

Frontend/privacy.html, Frontend/terms.html
Fixed the Terms page
Fixes: #113 
- [Fixed the Terms page ] Added new feature
---
=> Fixed the Terms page

Frontend/privacy.html, Frontend/terms.html
Redirect urls of the terms page are working
Fixes: #117 
- [ Redirect urls of the terms page are working] Fixed bug
---
=> Redirect urls of the terms page are working

Frontend/blog.css, Frontend/blog.html, Frontend/card.css, Frontend/contributor.js, Frontend/privacy.html, Frontend/projectpage.html, Frontend/review.html, Frontend/terms.html
Darkmode added in the blog page 
Fixes: #176 
- [ Darkmode added in the blog page ] Added new feature
---
=> Darkmode added in the blog page 

Frontend/privacy.html, Frontend/projectpage.html, Frontend/terms.html
project nav fixed
Fixes: #141
- [ project nav fixed] Fixed bug
---
=> project nav fixed

Frontend/card.css, Frontend/privacy.html, Frontend/projectpage.html, Frontend/terms.html
fixed the darkmode issue in greetings
Fixes: #150 
- [ fixed the darkmode issue in greetings] Added new feature
---
=> fixed the darkmode issue in greetings

Frontend/card.css, Frontend/privacy.html, Frontend/projectpage.html, Frontend/review.html, Frontend/terms.html
Links for the Reviews fixed
Fixes: #162 
- [ Links for the Reviews fixed] Added new feature
---
=> Links for the Reviews fixed

Frontend/card.css, Frontend/contributor.js, Frontend/privacy.html, Frontend/projectpage.html, Frontend/review.html, Frontend/terms.html
Contributors list added
Fixes: #172 
- [ Contributors list added] Added new feature
https://github.com/user-attachments/assets/b5f27486-0100-40f8-aa29-6f4c10f493e2
---
=> Contributors list added

Frontend/blog.css, Frontend/blog.html, Frontend/card.css, Frontend/contributor.js, Frontend/privacy.html, Frontend/projectpage.html, Frontend/review.html, Frontend/terms.html
Added styles to the blog page 
Fixes: #174 
- [ Added styles to the blog page ] Added new feature
---
=> Added styles to the blog page 

Frontend/blog.css, Frontend/blog.html, Frontend/card.css, Frontend/contributor.js, Frontend/privacy.html, Frontend/projectpage.html, Frontend/review.html, Frontend/terms.html
Added the nav and footer to the blog page 
Fixes: #175 
- [Added the nav and footer to the blog page  ] Added new feature
---
=> Added the nav and footer to the blog page 

Frontend/blog.html, Frontend/contributor.html, Frontend/index.html, Frontend/privacy.html, Frontend/projectpage.html, Frontend/review.html, Frontend/terms.html
Fixed Website name in the footer
Fixes: #236 
---
=> Fixed Website name

Frontend/blog.html, Frontend/contributor.html, Frontend/index.html, Frontend/privacy.html, Frontend/project.css, Frontend/projectpage.html, Frontend/review.html, Frontend/terms.html
Fixed Overflow Bug—footer of the project page
Fixes: #239 
---
=> Fixed Overflow Bug - footer of  project page

Frontend/blog.html, Frontend/index.html
=> Logout feature added

Frontend/index.html
Fixes: #124
- [ .] Fixed bug
---
=> events link footer now redirect to main page event section

Frontend/index.html
=> search bar with filter added in project section

Frontend/blog.html, Frontend/index.html
=> Blog page modified with blogs,links,search filter , "no results found"

Frontend/blog.html, Frontend/event.html, Frontend/index.html
=> Event page navbar & footer added

Frontend/index.html, Frontend/style.css
=> navbar overlapping issue #157 fixed!

Frontend/index.html
website link - https://guessing-gameonline.netlify.app/
Fixes: #130 
---
=> Guessing game website added.

Frontend/event.html, Frontend/leaderboard.html, Frontend/leaderboard1.html, Frontend/leaderboard2.html
Fixes: #153
like this , I have added 3 leaderboards.
---
=> leaderboard added for past 3 events

Frontend/event.html, Frontend/leaderboard.html, Frontend/leaderboard1.html, Frontend/leaderboard2.html
=> registration pages added for upcoming events

Frontend/privacy.html
Fixed Overflow Bug- footer of privacy page
Fixes: #238 
---
=> Fixed Overflow Bug- footer of privacy page

Frontend/event.html, Frontend/style.css
Fixed the alignment and responsiveness of footer
Fixes: #272 
Fixed the alignment and responsiveness of footer of the event page
Previous:
Now:
https://github.com/user-attachments/assets/30515623-ae74-419d-97ae-0ec2afbcc99b
Thank You
---
=> Fixed the alignment and responsiveness of footer in event page

Frontend/codingclub.png
Added logo to the page
Fixes: #201 
Added logo to the page
Previous:
Now:
Thank You
---
=> Added logo

Frontend/index.html
The issue #158 is fixed @ak-0283
=> issue #158 dark mode fix in events page

Frontend/style.css
Fixed the width of navbar
Fixes: #112 
Fixed the width of the navbar
Previous:
Now:
Thank You
---
=> Fixed the width of navbar

Frontend/index.html
=> no search result added in event search bar

Frontend/index.html
Fixes: #190
- [.] Code follows project guidelines
---
=> About us page expanded

Frontend/index.html
=> Faq search bar updated  with "no results found"

Frontend/style.css
=> Subscribe button responsiveness added

Frontend/signup.css, Frontend/signup.html, Frontend/signup.js
=> toggle eye implemented in sign up form.

Frontend/login.css, Frontend/login.html, Frontend/login.js
=> eye added in login page

Frontend/contributor.js, Frontend/index.html
=> Contributor page "no result found" added

Frontend/projectpage.html, Frontend/quiz.html
=> quiz app added in view demo  button

Frontend/projectpage.html
here is the website link - https://drumkit-by-codingclub.netlify.app/
Fixes: #252
---
=> Drum kit website added

Frontend/projectpage.html
https://codingclub-dictionary.netlify.app/
so, i mistakenly named the commit "drum kit added", it should be "dictionary added"
Fixes: #254
---
=> Dictionary website added

Frontend/projectpage.html
https://personalportfolio-codingclub.netlify.app/
Fixes: #253
---
=> Portfolio website added

Frontend/components/github.png, Frontend/components/linkidn.png, Frontend/index.html
Fixed Redirecting Icon Images
Fixes: #290
>Before
>After
---
=> Redirecting Icon fixed

Frontend/style.css
Fixed the footer
Fixes: #200 
The footer of the home page is fixed
Previous:
Now:
Thank You
---
=> Fixed the footer

Frontend/terms.html
Footer of Terms page
Fixes: #245 
---
=> Bug footer of terms Page

Frontend/index.html, Frontend/style.css
Fixed Navbar and footer of home page
Fixes: #308 
---
=> Fixed Navbar and footer of home page

Frontend/index.html, Frontend/style.css
Bug fix welcome user tag
Fixes: #273 
- [ Bug fix welcome user tag] Added new feature
---
=> Bug fix welcome user tag

Frontend/blog.html, Frontend/style.css
Fixed Navbar and footer of blog page
Fixes: #310 
---
=> Fixed Navbar and footer of blog page

Frontend/event.html, Frontend/index.html, Frontend/style.css
Fixed Navbar and Footer of more event page
Fixes: #312 
---
=> Fixed Navbar and Footer of more event page

Frontend/WeatherApp/weather.js, Frontend/event.html, Frontend/projectpage.html
Now you can add an event and delete an event and it wont get removed on re rendering the page 
Fixes: #215 
- [ Added dynamic button to the Event btn ] Added new feature
---
=> Added dynamic button to the Event btn 

Frontend/WeatherApp/weather.js, Frontend/event.html, Frontend/projectpage.html, Frontend/review.html
Fixed nav for mobile for reviews
Fixes: #222
- [ Fixed nav for mobile for reviews] Added new feature
---
=> Fixed nav for mobile for reviews

Frontend/WeatherApp/weather.js, Frontend/event.html, Frontend/projectpage.html, Frontend/review.html
Mobile nav for project page fixed
Fixes: #223 
- [Mobile nav for project page fixed ] Added new feature
---
=> Mobile nav for project page fixed

Frontend/WeatherApp/weather.js, Frontend/event.html, Frontend/projectpage.html, Frontend/review.html, Frontend/terms.html
Mobile nav for terms page added
Fixes: #224 
- [Mobile nav for terms page added ] Added new feature
---
=> Mobile nav for terms page added

Frontend/WeatherApp/weather.js, Frontend/contributor.html, Frontend/event.html, Frontend/projectpage.html, Frontend/review.html, Frontend/terms.html
Mobile navbar added for the Contibutors apge
Fixes: #225
- [ Mobile navbar added for the Contibutors apge] Added new feature
---
=> Mobile navbar added for the Contibutors apge

Frontend/download.jpg, Frontend/download.png, Frontend/index.html
Added social icons in contact form
Fixes: #205 
Added social icons in the contact page
Previous:
Now:
Thank You
---
=> Added social icons in contact form

Frontend/projectpage.html
Fixed Navbar of More Project page
Fixes: #313 
---
=> Fixed Navbar of More Project page

Frontend/privacy.html
Fixed navbar of privacy
Fixes: #315 
---
=> Bug navbar of  privacy

Frontend/style.css
Made the contact page responsive
Fixes: #271 
Made the contact page responsive
Previous:
Now:
Thank You
---
=> Made the contact page responsive

Frontend/index.html, Frontend/style.css
Fixed the image of about section
Fixes: #198 
Fixed the images of about section
Previous:
Now:
Thank You
---
=> Fixed the image of about section

Frontend/about.css, Frontend/blog.css, Frontend/contributor.css, Frontend/contributor.html, Frontend/event.css, Frontend/event.html, Frontend/index.html, Frontend/project.css, Frontend/projectpage.html, Frontend/review.html, Frontend/terms.html
added footer links in the terms page
Fixes: #295
- [added footer links in the terms page ] Fixed bug
---
=> added footer links in the terms page

Frontend/about.css, Frontend/blog.css, Frontend/contributor.css, Frontend/event.css, Frontend/index.html, Frontend/project.css, Frontend/review.html
Fixed the list styling
Fixes: #336 
- [Fixed the list styling ] Added new feature
---
=> Fixed the list styling

Frontend/about.css, Frontend/blog.css, Frontend/contributor.css, Frontend/contributor.html, Frontend/event.css, Frontend/event.html, Frontend/index.html, Frontend/project.css, Frontend/projectpage.html, Frontend/review.html
Added alert button on clciking the subscribe btn
Fixes: #300
- [ Added alert button on clciking the subscribe btn] Added new feature
---
=> Added alert button on clciking the subscribe btn

Frontend/about.css, Frontend/blog.css, Frontend/contributor.css, Frontend/contributor.html, Frontend/event.css, Frontend/event.html, Frontend/index.html, Frontend/project.css, Frontend/projectpage.html, Frontend/review.html
Fixed the mobile av for the navpage
Fixes: #306 
- [Fixed the mobile av for the navpage ] Added new feature
---
=> Fixed the mobile av for the navpage

Frontend/event.html, Frontend/event.js
Redirect urls added in the project page
Fixes: #214 
- [Redirect urls added in the project page ] Added new feature
---
=> Redirect urls added in the project page

Frontend/style.css
Made changes the title of the faq, feedback ,about ,etc
Fixes: #249 
- [ Made changes the title of the faq, feedback ,about ] Added new feature
---
=> Made changes the title of the faq, feedback ,about 

Frontend/contributor.html, Frontend/index.html, Frontend/projectpage.html, Frontend/review.html, Frontend/style.css
The issue #350 is fixed! @ak-0283 
Kindly add a diffuclty tag.
=> Added icons in the social links (issue #350)

Frontend/AllLoginPage/ailoginPage/ailogin.html, Frontend/AllLoginPage/beginloginPage/beginlogin.html, Frontend/AllLoginPage/loginPage/login.html, Frontend/AllLoginPage/stackloginPage/stacklogin.html, Frontend/blogPage/blog.html, Frontend/contributorPage/contributor.html, Frontend/eventPage/event.html, Frontend/index.html, Frontend/privacyPage/privacy.html, Frontend/projectPage/projectpage.html, Frontend/reviewPage/review.html, Frontend/signupPage/signup.html, Frontend/termsPage/terms.html
404 fixed file rendering
Fixes: #368 
- [ 404 fixed file rendering] Added new feature
https://github.com/user-attachments/assets/4d7943be-7579-49c1-bd12-ee998cf15f0c
---
=> 404 fixed file rendering

Frontend/index.html, Frontend/mainPage/style.css
Added Why Choose Us section
Fixes: #183 
. Added **Why Choose Us** section with structured layout  
. Improved responsiveness for **light & dark themes**  
. Refactored HTML structure for better readability  
- [yes] Code follows project guidelines
- [yes] Proper documentation updated
- [yes] Tested on local machine
=> Added Why Choose Us

Frontend/mainPage/style.css
Fixed the about section in dark mode
Fixes: #365
Fixed the background of about section and it's text color in the dark mode
Previous:
Now:
Thank You
---
=> Fixed the about section in dark mode

Frontend/signupPage/signup.css, Frontend/signupPage/signup.html
Added footer to the about page
Fixes: #372 
Added a responsive footer to the signup page
Preview:
Thank You
---
=> Added footer to the signup page

Frontend/User/user.html, Frontend/WeatherApp/weather.css, Frontend/contributorPage/contributor.html, Frontend/eventPage/event.html, Frontend/index.html, Frontend/privacyPage/privacy.html, Frontend/projectPage/projectpage.html, Frontend/reviewPage/review.html
Weather app styles added
Fixes: #258 
- [ Weather app styles added] Added new feature
---
=> Weather app styles added

Frontend/User/user.html, Frontend/index.html, Frontend/privacyPage/privacy.html
user profile addded
Fixes: #293 
- [ user profile addded] Added new feature
---
=> user profile addded

Frontend/User/user.html, Frontend/contributorPage/contributor.html, Frontend/eventPage/event.html, Frontend/index.html, Frontend/privacyPage/privacy.html, Frontend/projectPage/projectpage.html, Frontend/reviewPage/review.html
User profile tab adde in all nav
Fixes: #299
- [ User profile tab adde in all nav] Added new feature
---
=> User profile tab adde in all nav

Frontend/privacyPage/privacy.html
Footer fixed for privacy page
Fixes: #298 
- [Footer fixed for privacy page ] Added new feature
---
=> Footer fixed for privacy page

Frontend/reviewPage/review.css, Frontend/reviewPage/review.html
Fix the response issue in review page after 768px
Fixes: #362 
- Fixed the responsiveness issue on the review page for screen sizes greater than 768px.
- Ensured the layout adapts smoothly across different devices.
- Improved the UI for better user experience on tablets and larger screens.
---
=> Fix the response issue in review page after 768px

Frontend/signupPage/signup.html
Fixed 404 bug
Fixes: #379 
---
=> Fixed 404 bug

Frontend/quiz/quiz.html, Frontend/quiz/quiz.json
Api for quiz added
Fixes: #322
- [ Api for quiz added] Added new feature
https://github.com/user-attachments/assets/9cd62099-cf48-4f81-b59e-9ffa2c30ab37
---
=> Api for quiz added

Frontend/signupPage/signup.css, Frontend/signupPage/signup.html
Fixes: #380 
- Add feature
---
=> Design Footer

Frontend/projectPage/projectpage.html, Frontend/stopWatch/stopwatch.css, Frontend/stopWatch/stopwatch.html, Frontend/stopWatch/stopwatch.js
stopwatcgh added
Fixes: #231 
---
=> stopwatch added

Frontend/AllLoginPage/loginPage/login.css
=> Added margin

Frontend/signupPage/signup.css, Frontend/signupPage/signup.html
Added Validate phone input
Fixes: #383 
---
=> Added Validate phone input

Frontend/AllLoginPage/loginPage/login.css
Fixed Placeholder's size
Fixes: #384 
---
=> Fixed Placeholder's size

Frontend/privacyPage/privacy.css, Frontend/privacyPage/privacy.html
Redesigned ui of privacy page
Fixes: #237 
---
=> Redesigned ui of privacy page

Frontend/index.html, Frontend/resource/resource.css, Frontend/resource/resource.html
=> resources page added

Frontend/eventPage/event.html
=> More event page header ,footer modified with typing text, greeting card, dark mode functionality

Frontend/mainPage/style.css
Fixes: #188
- [ .] Fixed bug
---
=> Logo added in more event page

Frontend/index.html
=> Project search bar modified with "no search results"

Frontend/contributorPage/contributor.html
=> Contributor page footer modified with all links

Frontend/projectPage/projectpage.html
on clicking the levels, relevant projects will appear.
Fixes: #281
---
=> project level Section added

Frontend/index.html
Fixes: #302 
- [ .] Fixed bug
---
=> blog page navbar modified

Frontend/index.html
=> Projects section search bar modified with "no results found"

Frontend/eventPage/event.html, Frontend/leaderboard/leaderboard.html, Frontend/leaderboard/leaderboard1.html, Frontend/leaderboard/leaderboard2.html
=> navbar & footer added in all Leaderboard pages

Frontend/leaderboard/leaderboard.html, Frontend/leaderboard/leaderboard1.html, Frontend/leaderboard/leaderboard2.html
=> Scroll to top button added in all leaderboard pages

Frontend/AllLoginPage/beginloginPage/beginlogin.css, Frontend/AllLoginPage/beginloginPage/beginlogin.html
Added dark mode in begin hackathon login page
Fixes: #469 
- &#9745;  Added new feature
- &#9745; Code follows project guidelines
- &#9745; Proper documentation updated
- &#9745; Tested on local machine
---
=> Added dark mode in begin hackathon login page

Frontend/eventPage/event.css, Frontend/index.html, Frontend/mainPage/style.css
Fixed design of more event button
Fixes: #470 
---
=> Fixed design of more event button

Frontend/mainPage/style.css
Fixed alignment of footer
Fixes: #445 
---
=> Fixed alignment of footer(main page)

Frontend/AllLoginPage/loginPage/login.css
Update login page
Fixes: #242 
---
=> Update login page

Frontend/signupPage/signup.css
Update signup page
Fixes: #243 
---
=> Update signup page

Frontend/stopWatch/stopwatch.css
Made the stopwatch ui enhanced
Fixes: #397 
- [Made the stopwatch ui enhanced ] Added new feature
---
=> Made the stopwatch ui enhanced

Frontend/quiz/quiz.html
Adding darkmode to quiz app and back btn
Fixes: #420
---
=> Adding darkmode to quiz app and back btn

Frontend/Calculator/calculator.css, Frontend/Calculator/calculator.html, Frontend/Calculator/calculator.js, Frontend/NotesAPP/notes.css, Frontend/NotesAPP/notes.html, Frontend/NotesAPP/notes.js
ui improved and edit and notification added
Fixes: #451
---
=> ui improved and edit and notification added

Frontend/Calculator/calculator.css, Frontend/Calculator/calculator.html, Frontend/Calculator/calculator.js
UI IMPROVED and NUMPAD REQ ADDED
Fixes: #454 
---
=> UI IMPROVED and NUMPAD REQ ADDED

Frontend/typingSpeed/typingSpeed.css, Frontend/typingSpeed/typingSpeed.html, Frontend/typingSpeed/typingSpeed.js
Accuracy added and personal best added
Fixes: #453 
- [Accuracy added and personal best added ] Added new feature
---
=> Accuracy added and personal best added

Frontend/NotesAPP/notes.html, Frontend/index.html, Frontend/mainPage/style.css
search bar added to notes
Fixes: #461 
- [ search bar added to notes] Added new feature
---
=> search bar added to notes

Frontend/Dictionary/dictionary.html, Frontend/projectPage/projectpage.html
Dictionary added
Fixes: #455 
- [Dictionary added ] Added new feature
---
=> Fixed Dictionary 

Frontend/index.html, Frontend/password generator/passgen.html
Fixed password generator
Fixes: #457 
- [Fixed password generator ] Added new feature
---
=> Fixed password generator

Frontend/index.html, Frontend/password generator/passgen.html
fixed guessing game 
Fixes: #458 
- [fixed guessing game  ] Added new feature
---
=> fixed guessing game 

Frontend/guessing game/guessGame.html, Frontend/index.html, Frontend/mainPage/style.css, Frontend/todo/todo.html
fixed the todo
Fixes: #459 
- [fixed the todo ] Added new feature
---
=> fixed the todo

Frontend/User/user.html, Frontend/contributorPage/contributor.html, Frontend/eventPage/event.html, Frontend/index.html, Frontend/projectPage/projectpage.html, Frontend/reviewPage/review.html
Added User Profile page
Fixes: #482 
---
=> Added User Profile page

Frontend/index.html, Frontend/mainPage/style.css
Fixed Container view
Fixes: #481 
---
=> Fixed Container view

Frontend/index.html
Added Validation on feedback form
Fixes: #508 
---
=> Added Validation on feedback form

Frontend/User/user.html
Added Dark mode on User Profile
Fixes: #510 
---
=> Added Dark mode on User Profile

Frontend/contributorPage/contributor.css
Fixed container of contributor page
Fixes: #511 
---
=> Fixed container of contributor page

Frontend/WeatherApp/weather.css, Frontend/WeatherApp/weather.html, Frontend/WeatherApp/weather.js
Added Dark mode on weather app
Fixes: #517 
---
=> Added Dark mode on weather app

Frontend/quiz/quiz.html
Fixed over flow and back button (quiz app)
Fixes: #518 
---
=> Fixed over flow and back button(quiz app)

Frontend/Calculator/calculator.css, Frontend/Calculator/calculator.html, Frontend/Calculator/calculator.js
Added Custom scrollbar and change light mode theme and added dark mode
Fixes: #521 
---
=> Added Custom scrollbar and change light mode theme and added dark mode

Frontend/Calculator/calculator.js
Fixed bug of functionality
Fixes: #522 
---
=> Fixed bug of functionality(calculator)

Frontend/ExpenseTracker/expenseTracker.html, Frontend/ExpenseTracker/expenseTracker.js, Frontend/ExpenseTracker/expensetracker.css
Implemented Dark mode and back button
Fixes: #526 
---
=> Implemented Dark mode and back button

Frontend/currencyConverter/currency.css, Frontend/currencyConverter/currency.js, Frontend/currencyConverter/index.html
Implemented dark mode on currency converter
Fixes: #527 
---
=> Implemented dark mode on currency converter

Frontend/NotesAPP/notes.css, Frontend/NotesAPP/notes.html, Frontend/NotesAPP/notes.js, Frontend/quiz/quiz.html
Redesigned note app, added dark mode, added custom scrollbar, fixed quiz dark mode
Fixes: #524 
---
=> Redesigned note app, added dark-mode, added custom scrollbar, fixed quiz dark mode

Frontend/currencyConverter/index.html, Frontend/passwordGenerator/Coding Club-Projects and 3 more pages - Subhas - Microsoft​ Edge 05-03-2025 18_20_49.png, Frontend/passwordGenerator/back.png, Frontend/passwordGenerator/index.html, Frontend/passwordGenerator/passApp.js, Frontend/passwordGenerator/style.css, Frontend/projectPage/projectpage.html
Add the Password Generator Project
It is a new features where user can generate password and copy it to use
Fixes: #530 
---
=> Add the password generator project

Frontend/Calculator/calculator.js, Frontend/ColorPicker/colorpicker.html
select button added in the color picker
Fixes: #392 
- [ select button added in the color picker] Added new feature
---
=> select button added in the color picker

Frontend/.gitignore, Frontend/projectPage/projectpage.html
Fixed the project page
Fixes: #486 
---
=> Fixed the project page

Frontend/Dictionary/dictionary.html
Word of the day and fav added
Fixes: #500
---
=> Word of the day and fav added

Frontend/guessing game/guessGame.html
Scoreboard and timer added
Fixes: #502 
---
=> Scoreboard and timer added

Frontend/ColorPicker/colorpicker.html
Added gradient generator
Fixes: #503
---
=> Added gradient generator

Frontend/ColorPicker/colorpicker.html, Frontend/Dictionary/dictionary.html, Frontend/password generator/passgen.html
Toaster added in passweord gen
Fixes: #504 
---
=> Toaster added in passweord gen

Frontend/Dictionary/dictionary.html
History and thesarus added
Fixes: #505 
---
=> History and thesarus added

Frontend/guessing game/guessGame.html, Frontend/password generator/passgen.html
darkmode added to the guessing game
Fixes: #506 
---
=> darkmode added to the guessing game

Frontend/Calculator/calculator.js, Frontend/contributorPage/contributor.html, Frontend/eventPage/event.html, Frontend/index.html, Frontend/projectPage/projectpage.html, Frontend/reviewPage/review.html
Profile btn fixed 
Fixes: #507
---
=> Profile btn fixed

Frontend/stopWatch/stopwatch.css, Frontend/stopWatch/stopwatch.html, Frontend/stopWatch/stopwatch.js
Darkmode added to the stopwatch
Fixes: #512 
---
=> Darkmode added to the stopwatch

Frontend/typingSpeed/typingSpeed.css, Frontend/typingSpeed/typingSpeed.html, Frontend/typingSpeed/typingSpeed.js
darkmode for the typing speed
Fixes: #513 
---
=> darkmode for the typing speed

Frontend/resource/resource.css, Frontend/resource/resource.html
Added custom scrollbar on resources page
Fixes: #543 
---
=> Added custom scrollbar on resources page

Frontend/blogPage/blog.css, Frontend/blogPage/blog.html
Fixed dark mode on blog page
Fixes: #544 
---
=> Fixed dark mode on blog page

Frontend/leaderboard/leaderboard.html, Frontend/leaderboard/leaderboard1.html, Frontend/leaderboard/leaderboard2.html
Fixed dark mode for all leaderboards
Fixes: #545 
---
=> Fixed dark mode for all leaderboards

Frontend/Projects/Bmi Calculator/bmi.css, Frontend/Projects/Bmi Calculator/bmi.html, Frontend/Projects/Bmi Calculator/bmi.js, Frontend/images/bmi.png, Frontend/projectPage/projectpage.html
Added New project BMI Calculator
Fixes: #582 
---
=> Added New project BMI Calculator

Frontend/Projects/Bmi Calculator/bmi.css, Frontend/Projects/Guess the Number/guess.css, Frontend/Projects/Guess the Number/guess.html, Frontend/Projects/Guess the Number/guess.js, Frontend/images/guess.png, Frontend/projectPage/projectpage.html
Implemented new project guess the number game with custom scrollbar
Fixes: #584 
---
=> Implemented new project guess the number game with custom scrollbar

Frontend/Projects/Guess the Number/guess.css, Frontend/Projects/Guess the Number/guess.html, Frontend/Projects/Guess the Number/guess.js
Implemented dark mode with back button on guess the number game
Fixes: #585 
---
=> Implemented dark mode with back button on guess the number game

Frontend/Projects/Memory Card Game/memory.css, Frontend/Projects/Memory Card Game/memory.html, Frontend/Projects/Memory Card Game/memory.js
Implemented dark mode with back button on memory card game
Fixes: #587 
---
=> Implemented dark mode with back button on memory card game

Frontend/Projects/Pomodoro Timer/pomodoro.css, Frontend/Projects/Pomodoro Timer/pomodoro.html, Frontend/Projects/Pomodoro Timer/pomodoro.js, Frontend/images/pomodoro.png, Frontend/projectPage/projectpage.html
Added new project - pomodoro timer
Fixes: #588 
---
=> Added new project - pomodoro timer

Frontend/Projects/Pomodoro Timer/pomodoro.css, Frontend/Projects/Pomodoro Timer/pomodoro.html, Frontend/Projects/Pomodoro Timer/pomodoro.js
Added Dark mode, custom scrollbar and back button on pomodoro timer
Fixes: #589 
---
=> Added Dark mode, custom scrollbar and back button on pomodoro timer

Frontend/Projects/Qr Code Generator/qr.css, Frontend/Projects/Qr Code Generator/qr.html, Frontend/Projects/Qr Code Generator/qr.js, Frontend/images/qr.png, Frontend/projectPage/projectpage.html
Added new project QR code generator with custom scrollbar
Fixes: #590 
---
=> Added new project QR code generator with custom scrollbar

Frontend/Projects/Qr Code Generator/qr.css, Frontend/Projects/Qr Code Generator/qr.html, Frontend/Projects/Qr Code Generator/qr.js
Added dark mode and back button on QR code generator
Fixes: #591 
---
=> Added dark mode and back button on QR code generator

Frontend/Projects/Simon Says Game/simon.css, Frontend/Projects/Simon Says Game/simon.html, Frontend/Projects/Simon Says Game/simon.js, Frontend/images/simon.png, Frontend/projectPage/projectpage.html
Added New project - Simon Says Game with custom scrollbar
Fixes: #592 
---
=> Added New project - simon says game with custom scrollbar

Frontend/Calculator/calculator.js, Frontend/Dictionary/dictionary.html, Frontend/User/edituser.html, Frontend/User/user.html
Added the edit profile fucntionality
Fixes: #540 
---
=> Added the edit profile fucntionality

Frontend/index.html, Frontend/mainPage/style.css
Fix website responsiveness across various screen sizes
Fixes: #436
---
=> Fixed website responsiveness across various screen sizes

Frontend/password generator/passgen.html
Saved password and toggle visibilty added
Fixes: #566 
---
=> Saved password and toggle visibilty added

Frontend/ColorPicker/colorpicker.html
gradient diraction maker and more gradient stops added
Fixes: #567 
---
=> gradient diraction maker and more gradient stops added

Frontend/ColorPicker/colorpicker.html
fav and gradient hsitory added
Fixes: #569 
---
=> fav and gradient hsitory added

Frontend/todo/todo.html
progress bar and temporary storage added
Fixes: #570 
---
=> progress bar and temporary storage added

Frontend/todo/todo.html
Adedd voice input 
Fixes: #571 
---
=> Adedd voice input 

Frontend/todo/todo.html
due dates and reminders added
Fixes: #572 
---
=> due dates and reminders added

Frontend/todo/todo.html
Adding categories and filter
Fixes: #573 
---
=> Adding categories and filter

Frontend/guessing game/guessGame.html, Frontend/todo/todo.html
Retry and category added
Fixes: #574 
---
=> Retry and category added

Frontend/guessing game/guessGame.html, Frontend/quiz/quiz.html
Progress bar and higlight red on worng ans and green on correct ans
Fixes: #575 
---
=> Progress bar and higlight red on worng ans and green on correct ans

Frontend/basicCalculator/basicCalculator.css, Frontend/basicCalculator/basicCalculator.html, Frontend/bubble_game/bubble.css, Frontend/bubble_game/bubble.html, Frontend/bubble_game/bubble.js, Frontend/images/bubble_game.jpg, Frontend/index.html
=> Dark mode calculator

Frontend/bubble_game/bubble.css, Frontend/bubble_game/bubble.html, Frontend/bubble_game/bubble.js
=> Dark mode bubble game

Frontend/resource/resource.html
=> navbar,footer added in resource page

Frontend/resource/resource.html
=> Resource page scroll button added

Frontend/resource/resource.css
=> Resource page dark mode enhanced

Frontend/leaderboard/leaderboard.html, Frontend/leaderboard/leaderboard1.html, Frontend/leaderboard/leaderboard2.html
Fixes: #415 
- .[ ] Added new feature
---
=> Leader page hover effect added in all pages

Frontend/leaderboard/leaderboard.html, Frontend/leaderboard/leaderboard1.html, Frontend/leaderboard/leaderboard2.html
=> Greeting card added in all leaderboard pages 

Frontend/blogPage/blog.html, Frontend/contributorPage/contributor.html, Frontend/index.html, Frontend/projectPage/projectpage.html, Frontend/resource/resource.html, Frontend/reviewPage/review.html
=> Svg logo added in place of png logo

Frontend/eventPage/event.html, Frontend/index.html
=> faq section toggle function  resolved

Frontend/index.html
=> Faq section search filter added

Frontend/signupPage/signup.html
=> Signup page footer links added

Frontend/index.html
The issue #351 is fixed @ak-0283
=> added a pop up feature on newsletter subscribe (issue #351)

Frontend/index.html, Frontend/mainPage/style.css, Frontend/projectPage/projectpage.html, Frontend/signupPage/signup.html
=> why Choose us page redesigned

Frontend/blogPage/blog.html, Frontend/contributorPage/contributor.html, Frontend/eventPage/event.html, Frontend/index.html, Frontend/leaderboard/leaderboard.html, Frontend/leaderboard/leaderboard1.html, Frontend/leaderboard/leaderboard2.html, Frontend/mainPage/style.css, Frontend/projectPage/projectpage.html, Frontend/resource/resource.css, Frontend/resource/resource.html, Frontend/reviewPage/review.html, Frontend/signupPage/signup.html
=> logo added in currency converter project

Frontend/projectPage/projectpage.html
=> Project page all footer links added

Frontend/privacyPage/privacy.css, Frontend/termsPage/terms.css
=> Privacy page logo fixed

Frontend/blogPage/blog.html, Frontend/contributorPage/contributor.html, Frontend/eventPage/event.html, Frontend/index.html, Frontend/leaderboard/leaderboard.html, Frontend/leaderboard/leaderboard1.html, Frontend/leaderboard/leaderboard2.html, Frontend/mainPage/style.css, Frontend/projectPage/projectpage.html, Frontend/resource/resource.css, Frontend/resource/resource.html, Frontend/reviewPage/review.html, Frontend/signupPage/signup.html, Frontend/termsPage/terms.css
=> Term page logo fixed

Frontend/blogPage/blog.css, Frontend/projectPage/projectpage.html
=> blog page responsiveness done

Frontend/blogPage/blog.css, Frontend/index.html, Frontend/mainPage/style.css, Frontend/projectPage/projectpage.html
=> project level option now visible in dark mode

Frontend/stopWatch/stopwatch.css, Frontend/stopWatch/stopwatch.html
Added back button on stop watch
Fixes: #670 
---
=> Added back button on stop watch

Frontend/projectPage/projectpage.html
Fixed footer of project page
Fixes: #720 
---
=> Fixed footer of project page

Frontend/AllLoginPage/ailoginPage/ailogin.css, Frontend/AllLoginPage/ailoginPage/ailogin.html, Frontend/AllLoginPage/beginloginPage/beginlogin.css, Frontend/AllLoginPage/beginloginPage/beginlogin.html, Frontend/AllLoginPage/loginPage/login.css, Frontend/AllLoginPage/loginPage/login.html, Frontend/AllLoginPage/stackloginPage/stacklogin.css, Frontend/AllLoginPage/stackloginPage/stacklogin.html
Added Footer and custom scrollbar on all login pages
Fixes: #710 
---
=> Added Footer and custom scrollbar on all login pages

Frontend/index.html
Fixed working of  Add event button and submit button
Fixes: #711 
---
=> Fixed working of  Add event button and submit button

Frontend/mainPage/style.css, Frontend/projectPage/project.css
Fixed Alignment of project search bar
Fixes: #708 
---
=> Fixed Alignment of project search bar

Frontend/AllLoginPage/ailoginPage/ailogin.html, Frontend/AllLoginPage/beginloginPage/beginlogin.html, Frontend/AllLoginPage/loginPage/login.html, Frontend/AllLoginPage/stackloginPage/stacklogin.html, Frontend/Calculator/calculator.html, Frontend/User/user.html, Frontend/quiz/quiz.html, Frontend/signupPage/signup.html
Fixed all back  button for correct redirection
Fixes: #712 
---
=> Fixed all back  button for correct redirection

Frontend/contributorPage/contributor.css
Designed contributor's view profile button
Fixes: #715 
---
=> Designed contributor's view profile button

Frontend/contributorPage/contributor.html
Fixed links of  footer in contributors page
Fixes: #716
---
=> Fixed links of  footer in contributors page

Frontend/ExpenseTracker/expenseTracker.html, Frontend/ExpenseTracker/expenseTracker.js, Frontend/ExpenseTracker/expensetracker.css
Fixed dark mode and functions in Expense Tracker
Fixes: #714 
---
=> Fixed dark mode and functions in Expense Tracker

Frontend/projectPage/projectpage.html
Fixed images of project page
Fixes: #666 
---
=> Fixed images of project page

Frontend/Projects/Age Calculator/age.css, Frontend/Projects/Age Calculator/age.html, Frontend/Projects/Age Calculator/age.js, Frontend/images/age.png, Frontend/projectPage/projectpage.html
Added new project age calculator
Fixes: #734 
---
=> Added new project age calculator

Frontend/Projects/Quotes Generator/quotes.css, Frontend/Projects/Quotes Generator/quotes.html, Frontend/Projects/Quotes Generator/quotes.js, Frontend/images/quotes.png, Frontend/projectPage/projectpage.html
Added New project Quotes Generator
Fixes: #736 
---
=> Added New project Quotes Generator

Frontend/Projects/Hangman Game/hangman.css, Frontend/Projects/Hangman Game/hangman.html, Frontend/Projects/Hangman Game/hangman.js, Frontend/images/hangman.png, Frontend/projectPage/projectpage.html
Added New project Hangman Game
Fixes: #739 
---
=> Added New project Hangman Game

Frontend/Projects/URL Shortener/url.css, Frontend/Projects/URL Shortener/url.html, Frontend/Projects/URL Shortener/url.js, Frontend/images/url.png, Frontend/projectPage/projectpage.html
Added New project URL Shortener
Fixes: #741 
---
=> Added New project URL Shortener

Frontend/Projects/Flappy Bird/flappy.css, Frontend/Projects/Flappy Bird/flappy.html, Frontend/Projects/Flappy Bird/flappy.js, Frontend/images/flippy.png, Frontend/projectPage/projectpage.html
Added New project Flippy Bird
Fixes: #743 
---
=> Added New project Flippy Bird

Frontend/Projects/Age Calculator/age.css, Frontend/Projects/Age Calculator/age.html, Frontend/Projects/Age Calculator/age.js
Implemented dark mode, back button and custom scrollbar on age calculator
Fixes: #735 
---
=> Implemented dark mode, back button and custom scrollbar on age calculator

Frontend/Projects/Quotes Generator/quotes.css, Frontend/Projects/Quotes Generator/quotes.html, Frontend/Projects/Quotes Generator/quotes.js
Implemented dark mode, back button and custom scrollbar on quotes generator
Fixes: #738 
---
=> Implemented dark mode, back button and custom scrollbar on quotes generator

Frontend/Projects/URL Shortener/url.css, Frontend/Projects/URL Shortener/url.html, Frontend/Projects/URL Shortener/url.js
Implemented dark mode, back button and custom scrollbar on url shortener
Fixes: #742 
---
=> Implemented dark mode, back button and custom scrollbar on url shortener

Frontend/Projects/Flappy Bird/flappy.css, Frontend/Projects/Flappy Bird/flappy.html, Frontend/Projects/Flappy Bird/flappy.js
Implemented dark mode, back button on flippy game
Fixes: #744 
---
=> Implemented dark mode, back button on flippy game

Frontend/typingSpeed/typingSpeed.css
fixed overflow in typing speed
Fixes: #745 
---
=> fixed overflow in typing speed

Frontend/eventPage/event.html
fixed profile link in event page
Fixes: #785 
---
=> fixed profile link in event page

Frontend/contributorPage/contributor.html, Frontend/resource/resource.html, Frontend/reviewPage/review.html
fixed profile link in all page
Fixes: #786 
---
=> fixed profile link in all page

Frontend/projectV2/petSim/index.html
Virtual pet simulator added
Fixes: #634 
---
=> Virtual pet simulator added

Frontend/projectV2/2048/index.html
2048 game added
Fixes: #635 
---
=> 2048 game added

Frontend/index.html, Frontend/mainPage/style.css
Fixed Dark mode for contact page
Fixes: #824 
---
=> Fixed Dark mode for contact page

Frontend/resource/resource.html
Fixed links of resources page
Fixes: #825
---
=> Fixed links of resources page

Frontend/projectPage/projectpage.html
Fixed Project page ui
Fixes: #827 
---
=> Fixed Project page ui

Frontend/typingSpeed/typingSpeed.css, Frontend/typingSpeed/typingSpeed.html, Frontend/typingSpeed/typingSpeed.js
Redesigned Typing speed
Fixes: #713 
---
=> Redesigned Typing speed

Frontend/Projects/AI Chatbot/ai.css, Frontend/Projects/AI Chatbot/ai.html, Frontend/Projects/AI Chatbot/ai.js
Added dark mode and back button on ai chatbot
Fixes: #788 
---
=> Added dark mode and back button on ai chatbot

Frontend/Projects/Snake Game/snake.css, Frontend/Projects/Snake Game/snake.html, Frontend/Projects/Snake Game/snake.js, Frontend/images/snake.png, Frontend/projectPage/projectpage.html
Added New Project snake game
Fixes: #835 
---
=> Added New Project snake game

Frontend/Projects/Breakout Game/breakout.css, Frontend/Projects/Breakout Game/breakout.html, Frontend/Projects/Breakout Game/breakout.js, Frontend/Projects/Snake Game/snake.css, Frontend/Projects/Snake Game/snake.html, Frontend/Projects/Snake Game/snake.js, Frontend/images/breakout.png, Frontend/images/snake.png, Frontend/projectPage/projectpage.html
Added New Project Breakout game
Fixes: #836 
---
=> Added New Project Breakout game

Frontend/Projects/Space Shooter Game/space.css, Frontend/Projects/Space Shooter Game/space.html, Frontend/Projects/Space Shooter Game/space.js, Frontend/images/space.png, Frontend/projectPage/projectpage.html
Added New Project Space Shooter game
Fixes: #837 
---
=> Added New Project Space Shooter game

Frontend/Projects/Platformer Game/platformer.css, Frontend/Projects/Platformer Game/platformer.html, Frontend/Projects/Platformer Game/platformer.js, Frontend/images/platformer.png, Frontend/projectPage/projectpage.html
Added New Project Platformer game
Fixes: #838 
---
=> Added New Project Platformer game

Frontend/Projects/Pong Game/pong.css, Frontend/Projects/Pong Game/pong.html, Frontend/Projects/Pong Game/pong.js, Frontend/images/pong.png, Frontend/projectPage/projectpage.html
Added New Project Pong game
Fixes: #839 
---
=> Added New Project Pong game

Frontend/Projects/Pong Game/pong.css, Frontend/Projects/Pong Game/pong.html, Frontend/Projects/Pong Game/pong.js
Added Dark mode and back button on pong game
Fixes: #840 
---
=> Added Dark mode and back button on pong game

Frontend/Projects/Pong Game/pong.css, Frontend/Projects/Snake Game/snake.css, Frontend/Projects/Snake Game/snake.html, Frontend/Projects/Snake Game/snake.js
Added Dark mode and back button on snake  game
Fixes: #841 
---
=> Added Dark mode and back button on snake  game

Frontend/Projects/Breakout Game/breakout.css, Frontend/Projects/Breakout Game/breakout.html, Frontend/Projects/Breakout Game/breakout.js
Added Dark mode and back button on breakout game
Fixes: #842 
---
=> Added Dark mode and back button on breakout game

Frontend/Projects/Space Shooter Game/space.css, Frontend/Projects/Space Shooter Game/space.html, Frontend/Projects/Space Shooter Game/space.js
Added Dark mode and back button on space shooter game
Fixes: #843 
---
=> Added Dark mode and back button on space shooter game

Frontend/projectV2/2048/index.html
Redesigned 2048 game
Fixes: #881 
---
=> Redesigned 2048 game

Frontend/images/2048.png, Frontend/projectPage/projectpage.html
Added 2048 game in more project page
Fixes: #880
---
=> Added 2048 game in more project page

Frontend/images/petsim.png, Frontend/projectPage/projectpage.html
Added Virtual Pet Simulator in more project page
Fixes: #882
---
=> Added Virtual Pet Simulator in more project page

Frontend/projectPage/projectpage.html
=> Bookmark feature added for all projects card

Frontend/projectPage/projectpage.html
=> weather app view count added

Frontend/projectPage/projectpage.html
=> Quiz app count added

Frontend/projectPage/projectpage.html
=> Stop watch count added

Frontend/projectPage/projectpage.html
=> Calculator count added

Frontend/projectPage/projectpage.html
=> Notes app counter added

Frontend/projectPage/projectpage.html
=> Drum kit counter added

Frontend/projectPage/projectpage.html
=> Typing  speed test counter added

Frontend/projectPage/projectpage.html
=> Expense tracker counter added

Frontend/projectPage/projectpage.html
=> Dictionary counter added

Frontend/projectPage/projectpage.html
=> Currency convertor counter added

Frontend/eventPage/event.html, Frontend/mainPage/style.css, Frontend/projectPage/project.css
Fixed Alignment of project
Fixes: #909 
---
=> Fixed Alignment of project

Frontend/projectV2/hangman/index.html
Hangman game added
Fixes: #636 
---
=> Hangman game added

Frontend/projectV2/rockPaperScissor/index.html
Added rock paper sissor
Fixes: #638
---
=> Added Rock papaer scissor

Frontend/projectV2/flashcard/index.html
Aded study tools
Fixes: #639
---
=> Aded study tools

Frontend/projectV2/calorieCounter/calorieCounter.html
Adedd calorie counter 
Fixes: #640 
---
=> Adedd calorie counter 

Frontend/projectV2/toerOfHanoi/index.html
tower of hanoi
Fixes: #642 
---
=> tower of hanoi

Frontend/projectV2/timezoneconverter/index.html
Time zone converter added
Fixes: #643
---
=> Time zone converter added

Frontend/projectV2/grocery/index.html
Grocery app adedd
Fixes: #644
---
=> Grocery app adedd

Frontend/projectV2/usernameGenertor/index.html
Random username generator added
Fixes: #645 
---
=> Random username generator added

Frontend/projectV2/loanEmiCalc/index.html
Added loan emi calculator
Fixes: #646 
---
=> Added loan emi calculator

Frontend/projectPage/projectpage.html
Fixes: #536
This project is a **_spooky, fun, buggy and interactive_** static website.
🌟 **FEATURES**
- Scary and annoying bugs: From BSOD pop-ups to distorted screens and more.
- Confusing UI elements: Designed to challenge debugging skills.
- Spooky vibes: Halloween-inspired design elements, sound effects, and eerie animations.
---
=> Added a Fun Debug Website #607

Frontend/projectV2/diceroller/index.html
Added virtual dice roller
Fixes: #647 
---
=> Added virtual dice roller

Frontend/projectV2/verseVibe/index.html
Added verse Vibe
Fixes: #648 
---
=> Added verse Vibe

Frontend/projectV2/workoutPlanner/index.html
Workout planner added
Fixes: #649 
---
=> Workout planner added

Frontend/projectV2/reflex tester/index.html
Reflex tester added
Fixes: #652 
---
=> Reflex tester added

Frontend/projectV2/reflex tester/index.html, Frontend/projectV2/trivia/index.html
Darkmode added
Fixes: #808 
---
=> Darkmode added

Frontend/projectV2/calorieCounter/calorieCounter.html, Frontend/projectV2/flashcard/index.html, Frontend/projectV2/guessTheFlag/index.html, Frontend/projectV2/hangman/index.html, Frontend/projectV2/mineswepper/index.html, Frontend/projectV2/rockPaperScissor/index.html, Frontend/projectV2/timezoneconverter/index.html, Frontend/projectV2/toerOfHanoi/index.html, Frontend/projectV2/workoutPlanner/index.html
darkmode added wp
Fixes: #810 
---
=> darkmode added wp

Frontend/projectV2/workoutPlanner/index.html
Darkmode added versevibe
Fixes: #809 
---
=> Darkmode added versevibe

Frontend/projectV2/workoutPlanner/index.html
Categories added to verseVibe
Fixes: #812 
---
=> Categories added to verseVibe

Frontend/projectV2/workoutPlanner/index.html
progress bar added
Fixes: #813 
---
=> progress bar added

Frontend/projectV2/timezoneconverter/index.html
live clock added 
Fixes: #816 
---
=> live clock added 

Frontend/projectV2/calorieCounter/calorieCounter.html
Progress and cat added
Fixes: #818
---
=> Progress and cat added

Frontend/projectV2/mineswepper/index.html
Reveal the mines
Fixes: #820
---
=> Reveal the mines

Frontend/projectPage/projectpage.html
Fixed Project page
Fixes: #919
---
=> Fixed Project page

Frontend/projectPage/projectpage.html
=> weather rate

Frontend/projectPage/projectpage.html
=> Stopwatch rate

Frontend/projectPage/projectpage.html
=> Calculator rate

Frontend/projectPage/projectpage.html
=> Notes app rate

Frontend/projectPage/projectpage.html
=> Drums kit rate

Frontend/projectPage/projectpage.html
=> Typing speed rate

Frontend/projectPage/projectpage.html
=> Expense tracker rate

Frontend/projectPage/projectpage.html
=> Dictionary app rate

Frontend/projectPage/projectpage.html
=> Portfolio website rate

Frontend/projectPage/projectpage.html
=> Password generator rate

Frontend/projectPage/projectpage.html
=> Password generator view counter added

Frontend/projectPage/projectpage.html
=> Bmi calculator view counter added

Frontend/projectPage/projectpage.html
=> Guess game view

Frontend/projectPage/projectpage.html
=> Pomodoro view
